### PR TITLE
private method `print' called for 206:Fixnum (NoMethodError)

### PR DESCRIPTION
**Pull request by Peeja**
Hello, 

Im running on osx mountain lion and am running ruby 1.8.

I have installed the command line tools.
Installed the gem
And ran the example.rb but i get 
/Library/Ruby/Gems/1.8/gems/ruby-progressbar-1.0.2/lib/progress_bar/base.rb:101:in `clear': private method`print' called for 206:Fixnum (NoMethodError)
    from /Library/Ruby/Gems/1.8/gems/ruby-progressbar-1.0.2/lib/progress_bar/base.rb:27:in `start'
    from /Library/Ruby/Gems/1.8/gems/ruby-progressbar-1.0.2/lib/progress_bar/base.rb:20:in`initialize'
    from /Library/Ruby/Gems/1.8/gems/ruby-progressbar-1.0.2/lib/ruby-progressbar.rb:17:in `new'
    from /Library/Ruby/Gems/1.8/gems/ruby-progressbar-1.0.2/lib/ruby-progressbar.rb:17:in`create'
    from /Library/Ruby/Gems/1.8/gems/ruby-progressbar-1.0.2/lib/ruby-progressbar.rb:13:in `new'
    from /Library/Ruby/Gems/1.8/gems/multi_progress_bar-0.3.0/lib/multi_progress_bar/bar.rb:30:in`initialize'
    from ./tasklist_daemon.rb:13:in `new'
    from ./tasklist_daemon.rb:13
    from ./tasklist_daemon.rb:14:in`[]'
    from ./tasklist_daemon.rb:14

Do you know if this gem works with ruby 1.8?

Many thanks

### CODE REVIEW

**Comment by Peeja** [comment]
Hmm, it was written for 1.8, long before 1.9 was released.  Let me see if I can reproduce the error.

**Comment by Peeja** [comment]
Ugh, such old code.  I'm not sure if that fixes it.  Can you give it a try?  I just set the dependency on the old version of ruby-progressbar; the new one is incompatible.  It would be a lot better to update this gem to work with the new version.  And to use Bundler instead of Jeweler.

I don't use this library anymore, and I don't have much time to maintain it, but I'll gladly accept pull requests if you can fix it up.

**Comment by glitcha** [comment]
Hi Peeja, thanks for the response.

Sorry this is only my second day using ruby, how do i update my gem from this?

**Comment by Peeja** [comment]
Ah, well, it's not going to be easy, because this was written before the Ruby world got good a this sort of thing.  I'll try to find some time to fix it up for real soon and release a new version through Rubygems.

In the meantime, another solution occurs to me.  The problem is that multi_progress_bar needs an old version of ruby-progressbar, but doesn't specify it explicitly.  RubyGems is using the newest version it can get its hands on, because it doesn't know not to.  In _your_ project, you can add a dependency on ruby-progressbar v0.0.9 and it should load the right one, making everything work.

If you're using Bundler, that means adding

``` ruby
gem 'ruby-progressbar', '0.0.9'
```

to your `Gemfile`.  If you're writing a gem, instead add

``` ruby
gem.add_runtime_dependency 'ruby-progressbar', '0.0.9'
```

to your Gemspec.  If you're not managing dependencies at all, just playing around using what's installed in RubyGems, uninstall ruby-progressbar and install the right version:

``` sh
$ gem uninstall ruby-progressbar
$ gem install ruby-progressbar -v 0.0.9
```

Does that fix it?

**Comment by glitcha** [comment]
Thanks Peeja that works!

**Pull request closed without merging**
